# Form implementation generated from reading ui file 'desktop/ui_files/modal_profile.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserProfileModal(object):
    def setupUi(self, UserProfileModal):
        UserProfileModal.setObjectName("UserProfileModal")
        UserProfileModal.resize(400, 350)
        UserProfileModal.setStyleSheet("\n"
"     QDialog {\n"
"       background-color: white;\n"
"     }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(UserProfileModal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.titleLabel = QtWidgets.QLabel(parent=UserProfileModal)
        self.titleLabel.setStyleSheet("font-size: 16px; font-weight: bold; color: #333;")
        self.titleLabel.setObjectName("titleLabel")
        self.headerLayout.addWidget(self.titleLabel)
        self.verticalLayout.addLayout(self.headerLayout)
        self.line = QtWidgets.QFrame(parent=UserProfileModal)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.infoTopLayout = QtWidgets.QHBoxLayout()
        self.infoTopLayout.setObjectName("infoTopLayout")
        self.nameLayout = QtWidgets.QVBoxLayout()
        self.nameLayout.setObjectName("nameLayout")
        self.modalNameLabel = QtWidgets.QLabel(parent=UserProfileModal)
        self.modalNameLabel.setStyleSheet("font-size: 18px; font-weight: bold; color: #333;")
        self.modalNameLabel.setObjectName("modalNameLabel")
        self.nameLayout.addWidget(self.modalNameLabel)
        self.modalIdLabel = QtWidgets.QLabel(parent=UserProfileModal)
        self.modalIdLabel.setStyleSheet("font-size: 14px; color: #666;")
        self.modalIdLabel.setObjectName("modalIdLabel")
        self.nameLayout.addWidget(self.modalIdLabel)
        self.infoTopLayout.addLayout(self.nameLayout)
        self.modalStatusLabel = QtWidgets.QLabel(parent=UserProfileModal)
        self.modalStatusLabel.setStyleSheet("font-size: 14px; color: #28a745; font-weight: bold;")
        self.modalStatusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.modalStatusLabel.setObjectName("modalStatusLabel")
        self.infoTopLayout.addWidget(self.modalStatusLabel)
        self.verticalLayout.addLayout(self.infoTopLayout)
        self.infoTitleLabel = QtWidgets.QLabel(parent=UserProfileModal)
        self.infoTitleLabel.setStyleSheet("font-size: 14px; font-weight: bold; color: #333; margin-top: 10px;")
        self.infoTitleLabel.setObjectName("infoTitleLabel")
        self.verticalLayout.addWidget(self.infoTitleLabel)
        self.infoTextEdit = QtWidgets.QTextEdit(parent=UserProfileModal)
        self.infoTextEdit.setStyleSheet("\n"
"       QTextEdit {\n"
"         border: 1px solid #ddd;\n"
"         border-radius: 5px;\n"
"         padding: 8px;\n"
"         background-color: #f8f9fa;\n"
"       }\n"
"      ")
        self.infoTextEdit.setReadOnly(True)
        self.infoTextEdit.setObjectName("infoTextEdit")
        self.verticalLayout.addWidget(self.infoTextEdit)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.modalCloseBtn = QtWidgets.QPushButton(parent=UserProfileModal)
        self.modalCloseBtn.setStyleSheet("\n"
"         QPushButton {\n"
"           background-color: #6c757d;\n"
"           color: white;\n"
"           border: none;\n"
"           padding: 8px 16px;\n"
"           border-radius: 5px;\n"
"         }\n"
"         QPushButton:hover {\n"
"           background-color: #5a6268;\n"
"         }\n"
"        ")
        self.modalCloseBtn.setObjectName("modalCloseBtn")
        self.buttonLayout.addWidget(self.modalCloseBtn)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(UserProfileModal)
        QtCore.QMetaObject.connectSlotsByName(UserProfileModal)

    def retranslateUi(self, UserProfileModal):
        _translate = QtCore.QCoreApplication.translate
        UserProfileModal.setWindowTitle(_translate("UserProfileModal", "Профиль пользователя"))
        self.titleLabel.setText(_translate("UserProfileModal", "Профиль пользователя"))
        self.modalNameLabel.setText(_translate("UserProfileModal", "Имя пользователя"))
        self.modalIdLabel.setText(_translate("UserProfileModal", "ID: 12345"))
        self.modalStatusLabel.setText(_translate("UserProfileModal", "● В сети"))
        self.infoTitleLabel.setText(_translate("UserProfileModal", "Информация:"))
        self.modalCloseBtn.setText(_translate("UserProfileModal", "Закрыть"))
