# Form implementation generated from reading ui file 'desktop/ui_files/register.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 170)
        self.description = QtWidgets.QTextEdit(parent=Form)
        self.description.setGeometry(QtCore.QRect(190, 30, 191, 71))
        self.description.setObjectName("description")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        self.label.setObjectName("label")
        self.name_line = QtWidgets.QLineEdit(parent=Form)
        self.name_line.setGeometry(QtCore.QRect(20, 30, 141, 21))
        self.name_line.setObjectName("name_line")
        self.password_line = QtWidgets.QLineEdit(parent=Form)
        self.password_line.setGeometry(QtCore.QRect(20, 80, 141, 21))
        self.password_line.setObjectName("password_line")
        self.try_line = QtWidgets.QLineEdit(parent=Form)
        self.try_line.setGeometry(QtCore.QRect(20, 130, 141, 21))
        self.try_line.setObjectName("try_line")
        self.register_btn = QtWidgets.QPushButton(parent=Form)
        self.register_btn.setGeometry(QtCore.QRect(190, 119, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(11)
        self.register_btn.setFont(font)
        self.register_btn.setObjectName("register_btn")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 121, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 121, 21))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.label.setText(_translate("Form", "Введите ваше имя:"))
        self.register_btn.setText(_translate("Form", "Зарегистрироваться"))
        self.label_2.setText(_translate("Form", "Расскажите о себе:"))
        self.label_3.setText(_translate("Form", "Придумайте пароль:"))
        self.label_4.setText(_translate("Form", "Повторите пароль:"))
