# Form implementation generated from reading ui file 'desktop/ui_files/choice.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 132)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(28)
        Form.setFont(font)
        self.reg_btn = QtWidgets.QPushButton(parent=Form)
        self.reg_btn.setGeometry(QtCore.QRect(30, 20, 151, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.reg_btn.setFont(font)
        self.reg_btn.setObjectName("reg_btn")
        self.log_btn = QtWidgets.QPushButton(parent=Form)
        self.log_btn.setGeometry(QtCore.QRect(220, 20, 151, 91))
        self.log_btn.setObjectName("log_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sign in/Sign up"))
        self.reg_btn.setText(_translate("Form", "Регистрация"))
        self.log_btn.setText(_translate("Form", "Вход"))
