# Form implementation generated from reading ui file 'desktop/ui_files/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(674, 390)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 671, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.chat = QtWidgets.QWidget()
        self.chat.setObjectName("chat")
        self.scroll_chat = QtWidgets.QScrollArea(parent=self.chat)
        self.scroll_chat.setGeometry(QtCore.QRect(10, 10, 651, 291))
        self.scroll_chat.setWidgetResizable(True)
        self.scroll_chat.setObjectName("scroll_chat")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 649, 289))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scroll_chat.setWidget(self.scrollAreaWidgetContents_2)
        self.message_line = QtWidgets.QLineEdit(parent=self.chat)
        self.message_line.setGeometry(QtCore.QRect(10, 310, 551, 20))
        self.message_line.setObjectName("message_line")
        self.message_btn = QtWidgets.QPushButton(parent=self.chat)
        self.message_btn.setGeometry(QtCore.QRect(570, 310, 91, 20))
        self.message_btn.setObjectName("message_btn")
        self.tabWidget.addTab(self.chat, "")
        self.users = QtWidgets.QWidget()
        self.users.setObjectName("users")
        self.label = QtWidgets.QLabel(parent=self.users)
        self.label.setGeometry(QtCore.QRect(10, 0, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_search = QtWidgets.QLineEdit(parent=self.users)
        self.line_search.setGeometry(QtCore.QRect(10, 20, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_search.setFont(font)
        self.line_search.setObjectName("line_search")
        self.scroll_user = QtWidgets.QScrollArea(parent=self.users)
        self.scroll_user.setGeometry(QtCore.QRect(10, 50, 651, 281))
        self.scroll_user.setWidgetResizable(True)
        self.scroll_user.setObjectName("scroll_user")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 649, 279))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout.setObjectName("gridLayout")
        self.scroll_user.setWidget(self.scrollAreaWidgetContents_3)
        self.my_btn = QtWidgets.QPushButton(parent=self.users)
        self.my_btn.setGeometry(QtCore.QRect(560, 0, 101, 41))
        self.my_btn.setObjectName("my_btn")
        self.tabWidget.addTab(self.users, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ТСВчат"))
        self.message_line.setPlaceholderText(_translate("MainWindow", "Сообщение"))
        self.message_btn.setText(_translate("MainWindow", "Отправить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat), _translate("MainWindow", "Чат"))
        self.label.setText(_translate("MainWindow", "Поиск пользователей"))
        self.line_search.setPlaceholderText(_translate("MainWindow", "Введите имя"))
        self.my_btn.setText(_translate("MainWindow", "Мой профиль"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.users), _translate("MainWindow", "Пользователи"))
