# Form implementation generated from reading ui file 'desktop/ui_files/profile.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserCard(object):
    def setupUi(self, UserCard):
        UserCard.setObjectName("UserCard")
        UserCard.resize(300, 90)
        UserCard.setStyleSheet("\n"
"     QWidget#UserCard {\n"
"       background-color: white;\n"
"       border: 1px solid #ddd;\n"
"       border-radius: 8px;\n"
"       padding: 8px;\n"
"     }\n"
"     QWidget#UserCard:hover {\n"
"       border-color: #0084ff;\n"
"       background-color: #f8f9fa;\n"
"     }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(UserCard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")
        self.nameLabel = QtWidgets.QLabel(parent=UserCard)
        self.nameLabel.setStyleSheet("font-weight: bold; font-size: 14px; color: #333;")
        self.nameLabel.setObjectName("nameLabel")
        self.topLayout.addWidget(self.nameLabel)
        self.detailsBtn = QtWidgets.QPushButton(parent=UserCard)
        self.detailsBtn.setMaximumSize(QtCore.QSize(25, 25))
        self.detailsBtn.setStyleSheet("\n"
"         QPushButton {\n"
"           border: none;\n"
"           background-color: transparent;\n"
"           font-size: 16px;\n"
"         }\n"
"         QPushButton:hover {\n"
"           background-color: #e9ecef;\n"
"           border-radius: 3px;\n"
"         }\n"
"        ")
        self.detailsBtn.setObjectName("detailsBtn")
        self.topLayout.addWidget(self.detailsBtn)
        self.verticalLayout.addLayout(self.topLayout)
        self.middleLayout = QtWidgets.QHBoxLayout()
        self.middleLayout.setObjectName("middleLayout")
        self.idLabel = QtWidgets.QLabel(parent=UserCard)
        self.idLabel.setStyleSheet("font-size: 11px; color: #666;")
        self.idLabel.setObjectName("idLabel")
        self.middleLayout.addWidget(self.idLabel)
        self.statusLabel = QtWidgets.QLabel(parent=UserCard)
        self.statusLabel.setStyleSheet("font-size: 11px; color: #28a745;")
        self.statusLabel.setObjectName("statusLabel")
        self.middleLayout.addWidget(self.statusLabel)
        self.verticalLayout.addLayout(self.middleLayout)
        self.infoLabel = QtWidgets.QLabel(parent=UserCard)
        self.infoLabel.setStyleSheet("font-size: 12px; color: #444;")
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        self.infoLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)

        self.retranslateUi(UserCard)
        QtCore.QMetaObject.connectSlotsByName(UserCard)

    def retranslateUi(self, UserCard):
        _translate = QtCore.QCoreApplication.translate
        self.nameLabel.setText(_translate("UserCard", "Имя пользователя"))
        self.detailsBtn.setText(_translate("UserCard", "👁️"))
        self.idLabel.setText(_translate("UserCard", "ID: 12345"))
        self.statusLabel.setText(_translate("UserCard", "● В сети"))
        self.infoLabel.setText(_translate("UserCard", "Информация о пользователе которая не помещается в карточку и обрезается..."))
